---
kind: Service
apiVersion: v1
metadata:
    name: bglb
    labels:
        app: bglb
spec:
    ports:
        - port: 8000
          targetPort: 80
    selector:
        app: bluectl
    type: LoadBalancer
